import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

import { ReactQueryProvider } from "../providers/use-query";

export const metadata: Metadata = {
	title: "Doutor Agenda",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.svg",
	},
};

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReactQueryProvider> {children}</ReactQueryProvider>
				<Toaster position="bottom-center" richColors theme="light" />
			</body>
		</html>
	);
}
